import { execSync } from 'child_process'
import fs from 'fs'

const GENERATED_ARTIFACT_DIRS = ['specs', 'work-items']

function existingArtifactDirs(): string[] {
  return GENERATED_ARTIFACT_DIRS.filter((directory) => fs.existsSync(directory))
}

function commandExists(command: string): boolean {
  try {
    execSync(`command -v ${command}`, { stdio: 'inherit' })
    return true
  } catch {
    return false
  }
}

function isGitRepository(): boolean {
  try {
    execSync('git rev-parse --is-inside-work-tree', { stdio: 'inherit' })
    return true
  } catch {
    return false
  }
}

function hasGeneratedArtifactChanges(directories: string[]): boolean {
  if (directories.length === 0) {
    return false
  }

  const scopedDirs = directories.join(' ')
  try {
    execSync(`git diff --quiet -- ${scopedDirs}`, { stdio: 'inherit' })
    execSync(`git diff --cached --quiet -- ${scopedDirs}`, { stdio: 'inherit' })
    return false
  } catch {
    return true
  }
}

function buildBranchName(date: Date): string {
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  const hours = String(date.getHours()).padStart(2, '0')
  const minutes = String(date.getMinutes()).padStart(2, '0')
  return `muse/backlog-${year}-${month}-${day}-${hours}${minutes}`
}

export function prCommand(): void {
  if (!commandExists('git')) {
    throw new Error('Git is required to create a pull request.')
  }

  if (!isGitRepository()) {
    throw new Error('Current directory is not a git repository.')
  }

  if (!commandExists('gh')) {
    throw new Error('GitHub CLI (gh) is required to open a pull request.')
  }

  const artifactDirs = existingArtifactDirs()

  if (!hasGeneratedArtifactChanges(artifactDirs)) {
    process.stdout.write('No changes detected in generated artifact directories — nothing to commit.\n')
    return
  }

  const branch = buildBranchName(new Date())

  process.stdout.write(`Creating branch: ${branch}\n`)
  execSync(`git checkout -b ${branch}`, { stdio: 'inherit' })

  process.stdout.write('Staging generated artifacts\n')
  execSync(`git add ${artifactDirs.join(' ')}`, { stdio: 'inherit' })

  process.stdout.write('Committing changes\n')
  execSync('git commit -m "Muse: generated governance artifacts"', { stdio: 'inherit' })

  process.stdout.write('Pushing branch to origin\n')
  execSync(`git push origin ${branch}`, { stdio: 'inherit' })

  process.stdout.write('Opening pull request via GitHub CLI\n')
  execSync('gh pr create --title "Muse: Governance backlog update" --body "Artifacts generated by Muse CLI from governance documents."', {
    stdio: 'inherit',
  })

  process.stdout.write('Pull request created successfully.\n')
}
